In [1]:
import numpy as np

q = np.load('q.npy')
q1 = np.load('q30.npy')

In [2]:
q

array([0.99280578, 0.9942857 , 0.99504954, 0.99555552, 0.99592787,
       0.99621934, 0.99645388, 0.99665171, 0.99682271, 0.99697828,
       0.99710983, 0.99723244, 0.99734402, 0.99744576, 0.99753845,
       0.9976247 , 0.99770641, 0.9977833 , 0.99785721, 0.99792743,
       0.99799407, 0.99805444, 0.99811083, 0.99816686, 0.99822062,
       0.99827093, 0.99832076, 0.99836737, 0.99841267, 0.99845761,
       0.9985019 , 0.99854332, 0.99858356, 0.99862069, 0.99865955,
       0.99869841, 0.99873579, 0.99877149, 0.99880576, 0.99884123,
       0.9988755 , 0.99890834, 0.99894184, 0.9989776 , 0.99901187,
       0.99904484, 0.99907905, 0.99911171, 0.99914455, 0.99917692,
       0.99920881, 0.9992407 , 0.9992727 , 0.99930406, 0.99933594,
       0.99936879, 0.99940223, 0.99943572, 0.99947226, 0.99951178,
       0.99955553, 0.99959981, 0.99964839, 0.99970645, 0.99978292,
       1.0001086 , 1.00024772, 1.00031888, 1.00037634, 1.00042665,
       1.00047457, 1.00051975, 1.00056016, 1.00059772, 1.00063

In [3]:
q1

array([0.97565216, 0.98084503, 0.9835555 , 0.98535258, 0.98667341,
       0.98771822, 0.98857147, 0.9892934 , 0.98991752, 0.9904632 ,
       0.99095315, 0.99138993, 0.99179155, 0.99215865, 0.99249685,
       0.9928059 , 0.99310327, 0.99337745, 0.99363244, 0.99388146,
       0.99411726, 0.9943341 , 0.99454302, 0.99474442, 0.99494082,
       0.9951219 , 0.99529845, 0.99547505, 0.9956407 , 0.99580282,
       0.99596196, 0.99611402, 0.99626142, 0.9964028 , 0.99653983,
       0.99667746, 0.99680483, 0.99693578, 0.99706292, 0.99718559,
       0.99730664, 0.9974277 , 0.99754238, 0.99765289, 0.99776888,
       0.99788141, 0.99799639, 0.99810249, 0.99821138, 0.99831951,
       0.99842501, 0.99853367, 0.99863762, 0.99874848, 0.99885839,
       0.99897629, 0.99910587, 0.99924403, 0.99939942, 0.99962556,
       0.99999958, 0.9999997 , 0.99999982, 0.99999988, 0.99999994,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.00000012, 1.00000024, 1.00000083, 1.00051

In [4]:
import numpy as np

x = np.load('../data/train.npy')

x = x.reshape(-1, 119)

y = np.prod(np.lib.stride_tricks.sliding_window_view(x, (1,30)), axis=-1)

In [2]:
y.shape

(21336890, 90, 1)

In [5]:
q = np.quantile(y.flatten(), np.arange(0, 1, 1/127))

In [5]:
q[1:]

array([0.97565216, 0.98084503, 0.9835555 , 0.98535258, 0.98667341,
       0.98771822, 0.98857147, 0.9892934 , 0.98991752, 0.9904632 ,
       0.99095315, 0.99138993, 0.99179155, 0.99215865, 0.99249685,
       0.9928059 , 0.99310327, 0.99337745, 0.99363244, 0.99388146,
       0.99411726, 0.9943341 , 0.99454302, 0.99474442, 0.99494082,
       0.9951219 , 0.99529845, 0.99547505, 0.9956407 , 0.99580282,
       0.99596196, 0.99611402, 0.99626142, 0.9964028 , 0.99653983,
       0.99667746, 0.99680483, 0.99693578, 0.99706292, 0.99718559,
       0.99730664, 0.9974277 , 0.99754238, 0.99765289, 0.99776888,
       0.99788141, 0.99799639, 0.99810249, 0.99821138, 0.99831951,
       0.99842501, 0.99853367, 0.99863762, 0.99874848, 0.99885839,
       0.99897629, 0.99910587, 0.99924403, 0.99939942, 0.99962556,
       0.99999958, 0.9999997 , 0.99999982, 0.99999988, 0.99999994,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.00000012, 1.00000024, 1.00000083, 1.00051

In [6]:
np.save('q30.npy', q[1:])