In [32]:
import os
from os.path import join, getsize
import h5py
import torch


def get_file(file):
    with h5py.File(file, 'r') as f:
        ret = torch.tensor(f['values'])
        if (ret < 0).any():
            print(file, ret.nan_to_num(float('inf')).min())
        return ret

data = []
for root, dirs, files in os.walk('/data/share/data'):
    if 'valid_mask' in root:
        continue
    for file in files:
        if ('_' not in file or file[-5] == '_' and file[-4] == '0') and getsize(join(root, file)) == 163213752:
            data.append(get_file(join(root, file)).unsqueeze(0))

data = torch.concat(data)

print(data.shape)

/data/share/data/balance_sheet/surplus_reserve_mrq_0.h5 tensor(-1.0924e+09, dtype=torch.float64)
/data/share/data/balance_sheet/non_current_liability_due_one_year_mrq_0.h5 tensor(-9179661.1600, dtype=torch.float64)
/data/share/data/balance_sheet/bill_accts_payable_mrq_0.h5 tensor(-14103376.4800, dtype=torch.float64)
/data/share/data/balance_sheet/other_current_assets_mrq_0.h5 tensor(-59159739.7000, dtype=torch.float64)
/data/share/data/balance_sheet/surplus_reserve_lyr_0.h5 tensor(-1.0611e+09, dtype=torch.float64)
/data/share/data/balance_sheet/tax_payable_mrq_0.h5 tensor(-1.8410e+10, dtype=torch.float64)
/data/share/data/balance_sheet/financial_asset_held_for_trading_mrq_0.h5 tensor(-10076814.0800, dtype=torch.float64)
/data/share/data/balance_sheet/total_liabilities_lyr_0.h5 tensor(-2033023.6500, dtype=torch.float64)
/data/share/data/balance_sheet/other_payable_interest_dividend_mrq_0.h5 tensor(-36543527.2200, dtype=torch.float64)
/data/share/data/balance_sheet/total_construction_in_

In [36]:
torch.save(data.float(), 'company_basics.pt')

In [44]:
import os
from os.path import join, getsize
import h5py
import torch


def get_file(file):
    with h5py.File(file, 'r') as f:
        ret = torch.tensor(np.array(f['values'])[-3643:], dtype=torch.float32)
        if (ret < 0).any():
            print(file, ret.nan_to_num(float('inf')).min())
        return ret
data =  []
for root, dirs, files in os.walk('/data/share/data/daily/'):
    for file in files:
        if '_post' in file:
            data.append(get_file(join(root, file)).unsqueeze(0))
            print(file)

data = torch.concat(data)
print(data.shape)

limit_down_post.h5
high_post.h5
volume_post.h5
low_post.h5
close_post.h5
limit_up_post.h5
open_post.h5
torch.Size([7, 3643, 5480])


In [45]:
torch.save(data, 'prices.pt')

In [43]:
import numpy as np
with h5py.File('/data/share/data/daily/close_post.h5', 'r') as f:
    data = np.array(f['time'])[-3643:]
    print(data)

with h5py.File('/data/share/data/cash_flow_statement/cash_paid_for_other_financing_activities_lyr_1.h5', 'r') as f:
    data = np.array(f['time'])
    print(data)

[1262617200000000000 1262703600000000000 1262790000000000000 ...
 1735311600000000000 1735570800000000000 1735657200000000000]
[1262617200000000000 1262703600000000000 1262790000000000000 ...
 1735311600000000000 1735570800000000000 1735657200000000000]


In [28]:
map(lambda x: torch.sum(x < 0), data)

tensor([       0,        0,        0,        0,        0,      195,      358,
               0,      186,     1764,      233,   891698,        0,        0,
               0,        0,        0,     3000,      103,     1831,        0,
             296,        0,        0,        0,      363,     3212,        0,
          704072,      731,        0,      465,        0,        0,       66,
             315,    10004,     1128,        0,     3194,     3954,        0,
              66,        0,   721018,        0,      186,    40660,       40,
             994,        0,        0,        0,        0,     2936,  1636995,
            3947,      103,        0,      122,        0,        0,      860,
            1146,   661382,    90285,        0,      167,        0,        0,
             957,        0,        0,     1297,        0,   106519,      322,
             274,  1638614,   112950,      121,     1830,      478,    91257,
             808,        0,        0,        0,    39915,       

In [29]:
data[data < 0]

tensor([-2.6212e+07, -2.6212e+07, -2.6212e+07,  ..., -7.9222e+04,
        -5.7830e+08, -2.0000e+06], dtype=torch.float64)

In [ ]:
import torch
data = torch.tensor(data)
data = data.view(234, 3643, 5480)



In [24]:

ld = data.abs().log1p()

def a(data):
    return ((data.nan_to_num(0) - data.nan_to_num(0).to(torch.float32).to(torch.float64)).abs().max())

a(ld)

tensor(9.5367e-07, dtype=torch.float64)

In [23]:
map(a, data)

UncapturedHigherOrderOpError: map doesn't work unless it is captured completely with torch.compile. Scroll up to find out what causes the graph break.

from user code:
   File "/home/jkp/h/crsp/src/.venv/lib/python3.13/site-packages/torch/_higher_order_ops/map.py", line 187, in run_flattened_map
    return map_impl(inner_f, flat_xs, flat_args)

Set TORCHDYNAMO_VERBOSE=1 for the internal stack trace (please do this especially if you're reporting a bug to PyTorch). For even more developer context, set TORCH_LOGS="+dynamo"


In [33]:
import matplotlib.pyplot as plt
import h5py
import numpy as np
import torch
with h5py.File('/data/share/data/valid_mask/987a41e3.h5', 'r') as f:
    data = torch.tensor(np.array(f['values'])[:, :-153])

In [34]:
data.shape

torch.Size([3643, 5327])

In [36]:
torch.save(data, 'valid_mask.pt')

In [17]:
for i, x in enumerate(reversed(s)):
    if x:
        print(i)
        break

153


In [20]:
s[-153:].sum()

tensor(0)

In [4]:
data

tensor([True, True])

In [26]:
data = torch.load('company_basics.pt')

tensor([[[       nan,        nan, 2.6910e+08,  ...,        nan,
                 nan,        nan],
         [       nan,        nan, 2.6910e+08,  ...,        nan,
                 nan,        nan],
         [       nan,        nan, 2.6910e+08,  ...,        nan,
                 nan,        nan],
         ...,
         [       nan,        nan, 3.8447e+08,  ...,        nan,
                 nan,        nan],
         [       nan,        nan, 3.8447e+08,  ...,        nan,
                 nan,        nan],
         [       nan,        nan, 3.8447e+08,  ...,        nan,
                 nan,        nan]],

        [[1.9500e+07, 1.2887e+08, 1.2380e+09,  ...,        nan,
                 nan,        nan],
         [1.9500e+07, 1.2887e+08, 1.2380e+09,  ...,        nan,
                 nan,        nan],
         [1.9500e+07, 1.2887e+08, 1.2380e+09,  ...,        nan,
                 nan,        nan],
         ...,
         [       nan,        nan, 7.7660e+07,  ...,        nan,
               

In [27]:
data = data[:, :, :-153]

In [28]:
data.shape

torch.Size([234, 3643, 5327])

In [29]:
torch.save(data, 'company_basics.pt')